API_PORT: ":8088"
MetaNodeVersion: "0.0.1.0"
DnsLink_: "http://127.0.0.1:7080/api/dns/connection-address/"

ParentAddress: "9065e2caaa4bf6533ded0b2a763e4ee81cd31bd2"
NodeConnectionAddress: "node"
ParentConnectionAddress: "0.0.0.0:4200"
ParentConnectionType: "client"
ConnectionAddress_: "0x1eF5a8c5403c5aA1d43a8DC9eD391351012551Cf"
ChainId: 991

StorageAddress: "da7284faC5E804F8b9d71Aa39310f0f86776b51d"
StorageConnectionAddress: "storage"

PrivateKey_: "2b3aa0f620d2d73c046cd93eb64f2eb687a95b22e278500aa251c8c9dda1203b"

CardABIPath: "../abi/card.json"
CardAddress: "0x290eD8A174b03bc73dBb4F2E876d0E481C141A22"

ServerPrivateKeyPath: "./private_key"
AdminAddress: "24a71d62735be23ab6bc6b34df875235ff7b39e0" # Admin Address

PathLevelDB: "../db"
ThirdPartyApiUrl: "https://payment-card.vipn.net/transaction/create"
StoredPubKey: "./public_key"
RpcURL: "http://localhost:8545"
