API_PORT: ":8088"
MetaNodeVersion: "0.0.1.0"
DnsLink_: "http://rpc-proxy-sequoia.ibe.app:7080/api/dns/connection-address/"

NodeConnectionAddress: "node"
ParentConnectionAddress: "rpc-proxy-sequoia.ibe.app:4200"
ParentConnectionType: "client"
ConnectionAddress_: "0x1eF5a8c5403c5aA1d43a8DC9eD391351012551Cf"
ChainId: 991

StorageAddress: "da7284faC5E804F8b9d71Aa39310f0f86776b51d"
StorageConnectionAddress: "storage"

# ParentAddress: "7d7d9a12Fd6023AB4bB693F40F9b145F7C77Ecab"
# PrivateKey_: "89332ddc078676f6febf0b8218d3b6a11644c8901446bf5c158cb68a5ea7cee1"


CardABIPath: "../abi/card.json"
CardAddress: "0x10F4A365ff344b3Af382aBdB507c868F1c22f592"

ServerPrivateKeyPath: "./private_key"

AdminAddress: "D2bD184ef2375fe97D472B8139aa72A5C7B2063c" # Admin Address
PrivateKey_: "4a0bc835dcc74257a99b744ea0d86b3495c0fa16a88b36b6cdd3c66088825890"

PathLevelDB: "../db"
ThirdPartyApiUrl: "https://payment-card.vipn.net/transaction/create"
StoredPubKey: "./public_key"
RpcURL: "https://rpc-proxy-sequoia.iqnb.com:8446"

